server:
  port: 0000

spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/DB_name
      database: DB_name

eureka:
  client:
    serviceUrl:
      defaultZone: eureka_service_url