server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/database_name
    username: postgres
    password: 000000000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect